### ISSUE TITLE
An example how to read into a struct?

### ISSUE THREAD

**Issue by Slesa** [nathanjohnson320/ini#2]
Hi, thanks for your efforts. As a newby, I tried it on my own, but could you give me an example how to map the ini with possible defaults into some setup data? 

```ini
[Database]
Host = 192.168.1.42
User = postgres
; Port = 1234
[Log]
Level = debug
; File = application.log
```

into

```
%DatabaseSettings{host: string, user: string, port: integer}
%LogSettings{level: :debug, file: string} 
```

Maybe I can add a complete example then as PR? Or am I far away from the Elixir way?

**Comment by nathanjohnson320** [comment]
hello! This package wasn't really designed to have default values but you can kind of do them with structs in elixir.

I had to downcase the keys so they map properly but you can leave them uppercase just make sure they're the same case as the structs:


```elixir
defmodule Ini.ExampleTest do
  use ExUnit.Case

  test "parses into struct" do
    contents = """
    [database]
    host = 192.168.1.42
    user = postgres
    ; port = 1234
    [log]
    level = debug
    ; file = application.log
    """

    assert %{
             database: database,
             log: log
           } = Ini.decode(contents)

    assert %{host: "192.168.1.42", port: 1234, user: "postgres"} =
             struct!(DatabaseSettings, database)

    assert %{level: "debug", file: "application.log"} = struct!(LogSettings, log)
  end
end

defmodule DatabaseSettings do
  defstruct host: "", port: 1234, user: ""
end

defmodule LogSettings do
  defstruct level: "", file: "application.log"
end
```

**Comment by Slesa** [comment]
Thank you. Strange, the tests work great. But when I put exact the same content into the file, I get a mismatch:

```
(MatchError) no match of right hand side value: %{log: %{level: "debug"}, database: %{user: "postgres", host: "192.168.1.42"}}
```

with the code

```
    {:ok, ini} = File.read "./setup.ini"
    %{
      datase: database,
      log: log
      } = Ini.decode(ini)

```

Probably I have to work with get_in to find the section contents.

**Comment by nathanjohnson320** [comment]
I think it might be from the `datase ` instead of `database` on the left side of your `Ini.decode` causing that error

**Comment by Slesa** [comment]
How stupid... thanks again. I am not really convinced by this code. On the one hand there is the possibility of merging default settings and read settings. On the other hand I have my FSharp code where I read my settings via

```
 let config args : Settings =
     defaultSettings
     |> readEnvConfig
     |> readIniConfig
     |> readArgsConfig args
```

to have a hierarchy of configuration possibilities. But I have to wrap my head around Elixir's way first.
